import { SkillNode, UserStats, DailyLog } from './types';

export const mockNodes: SkillNode[] = [
  {
    id: 'root',
    label: 'Life Mastery',
    description: 'The foundation of all growth. Complete sub-skills to unlock your potential.',
    category: 'health',
    status: 'active',
    progress: 35,
    xpValue: 1000,
    prerequisites: [],
    tasks: [
      { id: 'r1', title: 'Define core values', completed: true, xpReward: 50 },
      { id: 'r2', title: 'Set 90-day vision', completed: true, xpReward: 50 },
      { id: 'r3', title: 'Weekly review ritual', completed: false, xpReward: 100 },
    ],
    position: { x: 400, y: 50 },
  },
  // DevOps Branch
  {
    id: 'linux',
    label: 'Linux Fundamentals',
    description: 'Master the command line, file system, and process management.',
    category: 'devops',
    status: 'completed',
    progress: 100,
    xpValue: 500,
    prerequisites: ['root'],
    tasks: [
      { id: 'l1', title: 'Complete Linux Journey', completed: true, xpReward: 100 },
      { id: 'l2', title: 'Bash scripting 101', completed: true, xpReward: 150 },
      { id: 'l3', title: 'Vim proficiency', completed: true, xpReward: 100 },
    ],
    position: { x: 100, y: 200 },
  },
  {
    id: 'docker',
    label: 'Docker & Containers',
    description: 'Containerize applications. Build images, compose services.',
    category: 'devops',
    status: 'active',
    progress: 65,
    xpValue: 600,
    prerequisites: ['linux'],
    tasks: [
      { id: 'd1', title: 'Dockerfile deep dive', completed: true, xpReward: 100 },
      { id: 'd2', title: 'Docker Compose multi-service', completed: true, xpReward: 150 },
      { id: 'd3', title: 'Container networking', completed: false, xpReward: 150 },
      { id: 'd4', title: 'Build production-grade image', completed: false, xpReward: 200 },
    ],
    position: { x: 100, y: 350 },
  },
  {
    id: 'k8s',
    label: 'Kubernetes',
    description: 'Orchestrate containers at scale. Pods, deployments, services.',
    category: 'devops',
    status: 'locked',
    progress: 0,
    xpValue: 800,
    prerequisites: ['docker'],
    tasks: [
      { id: 'k1', title: 'Minikube setup', completed: false, xpReward: 100 },
      { id: 'k2', title: 'Deployments & Services', completed: false, xpReward: 200 },
      { id: 'k3', title: 'Helm charts', completed: false, xpReward: 200 },
    ],
    position: { x: 100, y: 500 },
  },
  {
    id: 'cicd',
    label: 'CI/CD Pipelines',
    description: 'Automate testing and deployment. GitHub Actions, ArgoCD.',
    category: 'devops',
    status: 'locked',
    progress: 0,
    xpValue: 700,
    prerequisites: ['docker'],
    tasks: [
      { id: 'c1', title: 'GitHub Actions workflow', completed: false, xpReward: 150 },
      { id: 'c2', title: 'ArgoCD setup', completed: false, xpReward: 200 },
    ],
    position: { x: 250, y: 500 },
  },
  // Business Branch
  {
    id: 'meta-ads',
    label: 'Meta Ads Mastery',
    description: 'Run profitable campaigns for FigueStore. Targeting, creative, optimization.',
    category: 'business',
    status: 'active',
    progress: 40,
    xpValue: 500,
    prerequisites: ['root'],
    tasks: [
      { id: 'm1', title: 'Campaign structure setup', completed: true, xpReward: 100 },
      { id: 'm2', title: 'A/B test creatives', completed: false, xpReward: 150 },
      { id: 'm3', title: 'ROAS optimization', completed: false, xpReward: 200 },
    ],
    position: { x: 400, y: 200 },
  },
  {
    id: 'figue-growth',
    label: 'FigueStore Growth',
    description: 'Scale the e-commerce operation. Automation, new products.',
    category: 'business',
    status: 'available',
    progress: 10,
    xpValue: 600,
    prerequisites: ['meta-ads'],
    tasks: [
      { id: 'f1', title: 'Automate inventory alerts', completed: false, xpReward: 100 },
      { id: 'f2', title: 'Launch subscription model', completed: false, xpReward: 200 },
    ],
    position: { x: 400, y: 350 },
  },
  {
    id: 'ai-tutor',
    label: 'AI Tutor Launch',
    description: 'Deploy AI tutoring system for Cúcuta private schools.',
    category: 'business',
    status: 'locked',
    progress: 0,
    xpValue: 750,
    prerequisites: ['figue-growth'],
    tasks: [
      { id: 'a1', title: 'School partnership pitch', completed: false, xpReward: 150 },
      { id: 'a2', title: 'MVP tutoring engine', completed: false, xpReward: 300 },
    ],
    position: { x: 400, y: 500 },
  },
  // Teaching Branch
  {
    id: 'kubecraft',
    label: 'Kubecraft Bootcamp',
    description: 'Complete the DevOps bootcamp curriculum and projects.',
    category: 'teaching',
    status: 'active',
    progress: 55,
    xpValue: 700,
    prerequisites: ['root'],
    tasks: [
      { id: 'kb1', title: 'Module 1: Foundations', completed: true, xpReward: 100 },
      { id: 'kb2', title: 'Module 2: Containers', completed: true, xpReward: 100 },
      { id: 'kb3', title: 'Module 3: K8s basics', completed: false, xpReward: 150 },
      { id: 'kb4', title: 'Capstone project', completed: false, xpReward: 300 },
    ],
    position: { x: 700, y: 200 },
  },
  {
    id: 'hermes-exp',
    label: 'Hermes Agent Expert',
    description: 'Master the Hermes Agent framework. Become a regional expert.',
    category: 'teaching',
    status: 'available',
    progress: 25,
    xpValue: 800,
    prerequisites: ['kubecraft'],
    tasks: [
      { id: 'h1', title: 'Contribute 3 skills upstream', completed: false, xpReward: 200 },
      { id: 'h2', title: 'Train 2 local agents', completed: false, xpReward: 300 },
    ],
    position: { x: 700, y: 350 },
  },
  // Health Branch
  {
    id: 'morning',
    label: 'Morning Routine',
    description: 'Disciplined start. Meditation, planning, physical activation.',
    category: 'health',
    status: 'active',
    progress: 80,
    xpValue: 400,
    prerequisites: ['root'],
    tasks: [
      { id: 'mr1', title: 'Wake at 5:30 AM', completed: true, xpReward: 50 },
      { id: 'mr2', title: '10min meditation', completed: true, xpReward: 50 },
      { id: 'mr3', title: 'Journal + plan day', completed: true, xpReward: 50 },
      { id: 'mr4', title: 'Cold shower', completed: false, xpReward: 100 },
    ],
    position: { x: 550, y: 200 },
  },
  {
    id: 'deep-work',
    label: 'Deep Work Blocks',
    description: '4-hour focused sessions. No distractions, maximum output.',
    category: 'health',
    status: 'active',
    progress: 45,
    xpValue: 500,
    prerequisites: ['morning'],
    tasks: [
      { id: 'dw1', title: 'Phone in another room', completed: true, xpReward: 50 },
      { id: 'dw2', title: 'Pomodoro 4x daily', completed: false, xpReward: 100 },
      { id: 'dw3', title: 'Track focus score >80%', completed: false, xpReward: 150 },
    ],
    position: { x: 550, y: 350 },
  },
  {
    id: 'physical',
    label: 'Physical Training',
    description: 'Strength and conditioning. 4x per week minimum.',
    category: 'health',
    status: 'locked',
    progress: 0,
    xpValue: 450,
    prerequisites: ['morning'],
    tasks: [
      { id: 'pt1', title: 'Gym membership', completed: false, xpReward: 50 },
      { id: 'pt2', title: 'Complete 4 weeks', completed: false, xpReward: 150 },
    ],
    position: { x: 550, y: 500 },
  },
  // Creative Branch
  {
    id: 'goalboard-skill',
    label: 'GoalBoard OS',
    description: 'This application. Build the ultimate life dashboard.',
    category: 'creative',
    status: 'active',
    progress: 30,
    xpValue: 600,
    prerequisites: ['root'],
    tasks: [
      { id: 'gb1', title: 'Design system v1', completed: true, xpReward: 100 },
      { id: 'gb2', title: 'Skill tree visualization', completed: false, xpReward: 200 },
      { id: 'gb3', title: 'Analytics engine', completed: false, xpReward: 200 },
    ],
    position: { x: 850, y: 200 },
  },
  {
    id: 'enkephalos',
    label: 'Enkephalos Vault',
    description: 'Perfect the Zettelkasten + AI wiki knowledge system.',
    category: 'creative',
    status: 'available',
    progress: 60,
    xpValue: 500,
    prerequisites: ['goalboard-skill'],
    tasks: [
      { id: 'e1', title: 'Book ingestion pipeline', completed: true, xpReward: 150 },
      { id: 'e2', title: 'Auto-wiki generation', completed: false, xpReward: 200 },
    ],
    position: { x: 850, y: 350 },
  },
];

export const initialUserStats: UserStats = {
  level: 7,
  currentXp: 2450,
  xpToNextLevel: 3000,
  totalXp: 15450,
  streakDays: 12,
  longestStreak: 23,
  todayFocus: 'Docker & Containers',
  todayTasksCompleted: 3,
  todayTasksTotal: 7,
};

export const dailyLogs: DailyLog[] = [
  { date: '2026-04-07', xpEarned: 320, tasksCompleted: 5, focusMinutes: 240 },
  { date: '2026-04-08', xpEarned: 180, tasksCompleted: 3, focusMinutes: 180 },
  { date: '2026-04-09', xpEarned: 450, tasksCompleted: 7, focusMinutes: 300 },
  { date: '2026-04-10', xpEarned: 0, tasksCompleted: 0, focusMinutes: 0 },
  { date: '2026-04-11', xpEarned: 210, tasksCompleted: 4, focusMinutes: 200 },
  { date: '2026-04-12', xpEarned: 380, tasksCompleted: 6, focusMinutes: 280 },
  { date: '2026-04-13', xpEarned: 290, tasksCompleted: 5, focusMinutes: 220 },
  { date: '2026-04-14', xpEarned: 150, tasksCompleted: 2, focusMinutes: 120 },
  { date: '2026-04-15', xpEarned: 410, tasksCompleted: 7, focusMinutes: 310 },
  { date: '2026-04-16', xpEarned: 340, tasksCompleted: 6, focusMinutes: 260 },
  { date: '2026-04-17', xpEarned: 120, tasksCompleted: 2, focusMinutes: 90 },
  { date: '2026-04-18', xpEarned: 500, tasksCompleted: 8, focusMinutes: 360 },
  { date: '2026-04-19', xpEarned: 280, tasksCompleted: 5, focusMinutes: 210 },
  { date: '2026-04-20', xpEarned: 360, tasksCompleted: 6, focusMinutes: 270 },
  { date: '2026-04-21', xpEarned: 180, tasksCompleted: 3, focusMinutes: 150 },
];
